### ISSUE TITLE
[setup] Starting a project: out vision

### ISSUE THREAD

**Issue by vityaman** [Moleus/collective-edu#1]
# Initial problem statement

Create a separate discussion for your project group. Post there:
- your project title/focus (can be reformed in the process of project realization)
- iterations of the project realization (can be in random order, will be revised, ordered and commented on by the group members later)

**Comment by vityaman** [comment]
@Moleus, as I understand, to use GitHub Projects here you need to create one and link it to this repository. I tried to make a board, but was redirected to your profile. Maybe this is because I don't have enough permissions in this repository. So it would be nice if you give us role of maintainer to allow us to change some settings.

**Comment by moleus** [comment]
@vityaman I've checked the permissions and I can't change your status because there is only one - "collaborator". I've added the project board and invited all of you as admins

**Comment by vityaman** [comment]
# Our vision

I think to start we need to create a common vision of the project. By vision I mean:
- What are we creating (briefly)?
- What problems does it solve?
- Why that problems are important?
- How it will solve the problems (mechanism)?

So I'll want to share my ideas about it from my perspective.

## What are we creating

We want to create a service that will help people to pass tests on OpenEdu more easily by providing them some hints for a particular question right in their browser.

## What problems does it solve and why that problems are important

Sometimes test questions on the OpenEdu curses are extremely tricky while providing student with not so many attempts to guess the answer and no even tiny hints. Students struggle with it and we want to give them a relieve. This was a naive motivation for the project. The real is that we challenging distance education pointing to the knowledge checking system — tests are easy to cheat and therefore their results can't be cannot testify to the proper level of knowledge while remaining quite a good way to teach. Our attempt is to force online courses creators to use more proven methods for examination as tests under the proctoring, questions with a questions with a detailed answer and maybe some random generated tasks. This problem is very important as cases of cheating are usual on online courses, so we want to reduce them by a destruction of an unreliable educational system.

## How it will solve the problems (mechanism)

We want to create a Firefox (as it is OSS, and we respect it, unlike popular proprietary software) browser extension that will have an access to OpenEdu web page, it will parse its contents and take correct answers, send it to our backend service where answers will be stored and then other users will be able to get the answers right in their OpenEdu page using our extension, as it will take answers on the page, search for a solution in a database and provide it as a hint or just in a in a direct way or even automatically fill forms and push buttons.

So this was my point of view. People, what do you think about this? Maybe you have some additions or disagreements?

@Moleus @algoritmist @vuhtang

**Comment by algoritmist** [comment]
@vityaman the vision is well described
Talking about the mechanism, I guess the extension could also process wrong answers. It will be useful not only for deducing correct answers, but also when dealing with questions that have only one correct answer

**Comment by vityaman** [comment]
So, gentlemens, as we rather well described our vision, we can now move to the next stages, described in the issue https://github.com/Moleus/collective-edu/issues/2.

**Comment by vityaman** [comment]
## Output

- `MR` with the `doc/vision.md`.
