### ISSUE TITLE
[setup] Project roadmap

### ISSUE THREAD

**Issue by algoritmist** [Moleus/collective-edu#2]
I would like suggest the following roadmap:
* Determine our stakeholders [done]
* Determine requirements
* Understand the problem and brainstorm solutions
* Design app architecture
* Assign roles & tasks to team members
* Develop & test app using agile techniques
* Release

**Comment by vityaman** [comment]
@algoritmist, what do you think about adding one more step to plan prototype development iterations somewhere after the 2nd or 3rd points?

**Comment by vuhtang** [comment]
Seems like we're not using agile model.. Agile is about whole process, whole road map, not only developing and testing. Or I'm wrong.

**Comment by vityaman** [comment]
@vuhtang, I feel that you are right, but I can't spot an exact problem with our workflow. Let's discuss our understanding of agile and come up with an idea how to follow its rules correctly. 

For me agile is a waterfall model, but looped. Agile is an iterative model where we work with a prototype and add features there layer by layer. 

1. We have input data: this is tickets that are statements of problems which we need to solve.
2. We score them, prioritize and take some of them to the next sprint.
3. During the sprint we are working on these problems with the goal to create some kinda artifacts as a criteria of task completion.
4. Then we repeat the process from the start.

For example, this week we have the first sprint. Our goal was stated in the first ticket description originally expressed on the FLTC web site. So this is our input. Now we are working on building our product vision and coming up with functional requirements. After we get all requirements we will be able to plan some iterations of the project. Firstly there will be a goal to create an MVP with limited abilities. Then we will add some features step by step taking us closer and closer to the final product each time.

At my point of view what we need to do now is to extract functional requirements from our vision, then divide them into chain of subsets, each subset will be a set of requirements (we need to get required data automatically right from the web page, we need to store it in a persistent storage, ...) for a specific prototype version. Then we will take the first smallest subset of requirements and make some technical tasks (make an web service to store some data, make a browser extension client, ...). And then grab them and go crazy.

**Comment by algoritmist** [comment]
> @algoritmist, what do you think about adding one more step to plan prototype development iterations somewhere after the 2nd or 3rd points?

@vityaman Yes, I think we should work on the prototype as well

**Comment by moleus** [comment]
@vityaman if I understand you right, our current goal is the development of requirements for our project. What do you think about creating an SRS (software requirements specification) document? Maybe we can create REAMDE.md with key points for our project. 

Also, what about non-functional requirements? We can think about a user experience or maybe something related to our promises on how our software shall function

**Comment by moleus** [comment]
On the other hand SRS might be _too much_ for our small project. And I'm not sure that it'll correlate with agile style of development.

**Comment by vityaman** [comment]
@Moleus and @algoritmist, I think we can write some document with requirements just to fix them, but not so formal and serious as SRS, just requirements list with ids. 

Then we will link these ids with each prototype iteration. For example, assume we have `FR1-FR8` requirements, then prototype 1 must meet `FR1-3` and `FR5`, prototype 2 must meet previous plus `FR4`, prototype 3 must meet remaining.

Non-functional requirements should be included too, but I don't have ideas of them right now.

**Comment by vityaman** [comment]
My good gentlemen, here is draft of functional and non-functional requirements. Feel free to add your ideas and criticize mine. After a discussion will be finished we will be able to make a pull request to `doc` section. Also consider to create a separate ticket for requirements, link this comment and proceed a talk there, I leave it to you.

# Requirements

## Functional 

- **FR01** Service must have a client as a `Firefox` browser extension.
- **FR02** Service must get answers from an `OpenEdu` test page.
- **FR03** Service must store a test results in its database.
- **FR04** Service must provide users with hints for questions if it has enough information.
- **FR05** Service must be able to share test results between users.
- **FR06** Service must add control right in the `OpenEdu` page near each question to query a hint.
- **FR07** Service must automatically detect correct answers without additional user actions. 
- **FR08** Service must serve only authorized users. 
- **FR09** Service must support questions with a single answer.
- **FR10** Service must support questions with a multiple answer.
- **FR11** Service must support questions with a text input.

## Technical

- **TR1** Service must be able to handle 4 simultaneous users.
- **TR2** Service must have a latency no more than 10 seconds.

**Comment by vityaman** [comment]
And also my thoughts on project iterations.

# Project iterations

## `I1`: Proof of OpenEdu crackability

### Description

The simplest `Firefox` extension that just parses a page and extracts questions and answers on page reload, then sends it to the backend where it is stored in a database. Also on page reload it parses questions and queries answers from backend, results can be displayed just as an alert.

### Requirements

`FR1`, `FR2`, `FR3`, `FR4`, `FR5`, `FR09`.

## `I2`: Support for more tests

### Description

Add support for other test modes: multiple answers and text inputs.

### Requirements

`FR10`, `FR11`.

## `I3`: A better and dynamic UI

### Description

Add inline answers and buttons near each unanswered question input to query a specific answer.

## `I4`: Adding security and authorization

### Description

Secure backend from authorized access, don't serve strangers.

**Comment by vuhtang** [comment]
@vityaman I don't really understand the point of **FR5** , there is **FR4** which said that we will provide hints, correct answer or several wrong answers f.e., so what other results we will share?
