### ISSUE TITLE
[doc] Write the project requirements doc

### ISSUE THREAD

**Issue by moleus** [Moleus/collective-edu#4]
In this ticket we have to come up with the final requirements for our application.

Ideas by @vityaman are described here - https://github.com/Moleus/collective-edu/issues/2#issuecomment-1944393874

After the requirements are discussed and fixed this issue will be closed as completed

Initial version by Victor:
![image](https://github.com/Moleus/collective-edu/assets/66182149/53981fd2-3e8d-448e-bbc6-0b5d3df248e3)

**Comment by moleus** [comment]
I find `FR08` quite strange and kinda impossible to achieve. Anybody can install the extension or send the requests to backend server faking a browser. We can't identify a person other then asking to enter username/password. But it theoretically will come up with dozens of dummy accounts. We can ask for phone number and send SMS for verification, but I don't think that's worth it.

**Comment by moleus** [comment]
Never the less, I think that security is important part of the project. I have a few thoughts to discuss:
- How much data (approximately) shall be stored on server?
- How much traffic shall it handle? Can we protect against DoS?
- What about distributed way of storing data, people can setup backends on their own servers and browser will connect dynamically to them based on some rules?

**Comment by vityaman** [comment]
@Moleus, about `FR08`. We can add `Yandex OAuth 2` for an authentication, to solve this problem. Also I want to say that we can implement this requirement only at late iterations (that are unlikely to happen).

**Comment by vityaman** [comment]
@Moleus, what do you mean by
> After the requirements are discussed and fixed this issue will be closed as completed

Do I understand correctly, that we should create a specification document as this issue artifact (at `doc/design.md`) and only then close this? In case of yes, I can take it on me.

**Comment by moleus** [comment]
> @Moleus, about `FR08`. We can add `Yandex OAuth 2` for an authentication, to solve this problem. Also I want to say that we can implement this requirement only at late iterations (that are unlikely to happen).

Ok, haven't though about OAuth yet. And this is really promising solution

**Comment by moleus** [comment]
> @Moleus, what do you mean by
> 
> > After the requirements are discussed and fixed this issue will be closed as completed
> 
> Do I understand correctly, that we should create a specification document as this issue artifact (at `doc/design.md`) and only then close this? In case of yes, I can take it on me.

Yep, you are right. We can create a new file with these requirements and after that close the issue :+1:
